import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mạnh Hùng Portfolio',
  description: 'Generated by Nguyễn Mạnh Hùng',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`${inter.className} 
      bg-zinc-50 text-black relative h-[5000px]`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
