import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style/main.css";
import 'bootstrap/dist/css/bootstrap.css';
import Header from "@/components/header";

// Use the correct import syntax for the font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Mạnh Hùng Portfolio',
  description: 'Generated by Nguyễn Mạnh Hùng',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`root ${inter.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
